quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:MY}
quarkus.datasource.password=${DB_PASSWORD:TORQUATO}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:SONIC}

mp.jwt.verify.issuer=api-cisco
smallrye.jwt.always-check-authorization=true

hash.salt=LucianoDelRey
quarkus.hibernate-orm.database.generation=update
